import "server-only";

import { readFileSync } from "node:fs";
import path from "node:path";
import { CriteresFile, type Declinaison } from "@rgaa/content";
import type { Criterias, Test, Topic } from "~/components/rgaa/helpers/topics";
import type { ReferentielId } from "~/components/rgaa/referentiels";

const RGAA_VERSION = "5";

// Données publiées: generated by CI from rgaa/content/, read at build time by the static export.
const DATA_DIR = path.join(process.cwd(), "..", "..", "rgaa", "data");

let cache: CriteresFile | undefined;

function readCriteresFile(): CriteresFile {
	if (cache) return cache;
	const file = path.join(DATA_DIR, RGAA_VERSION, "criteres.json");
	cache = CriteresFile.parse(JSON.parse(readFileSync(file, "utf8")));
	return cache;
}

// Published numbers are absolute ("1.1", "1.1.1"); the accordions rebuild them from their parents.
const lastSegment = (number: string) =>
	number.slice(number.lastIndexOf(".") + 1);

function toTests(declinaison: Declinaison): Test[] {
	return declinaison.tests.map((test) => ({
		number: lastSegment(test.number),
		label: test.title,
		conditions: test.conditions ?? [],
		methodology: test.methodology,
	}));
}

export function getCriterias(reference: ReferentielId): Criterias {
	const { referentiels, topics } = readCriteresFile();
	const referentiel = referentiels.find(({ id }) => id === reference);

	if (!referentiel) throw new Error(`Référentiel inconnu: ${reference}`);

	const mapped: Topic[] = topics.map((topic) => {
		const criteria = topic.criteria.flatMap((critere) => {
			const declinaison = critere.referentiels[reference];
			const number = lastSegment(critere.number);

			return [
				{
					number,
					criterium: {
						number,
						title: critere.title,
						tests: !declinaison ? [] : toTests(declinaison),
						appendix: declinaison?.appendix,
					},
				},
			];
		});

		const hasTests = criteria.some(
			({ criterium }) => criterium.tests.length > 0,
		);

		return {
			topic: topic.title,
			number: Number(topic.number),
			criteria: hasTests ? criteria : [],
		};
	});

	return { referentiel: referentiel.title, topics: mapped };
}

export function getReferentiel(reference: ReferentielId) {
	const referentiel = readCriteresFile().referentiels.find(
		({ id }) => id === reference,
	);
	if (!referentiel) throw new Error(`Référentiel inconnu: ${reference}`);
	return referentiel;
}

export function getAllReferentiels() {
	return readCriteresFile().referentiels;
}
